export const ADD_TV_BOOKMARK = "ADD_TV_BOOKMARK";
export const REMOVE_TV_BOOKMARK = "REMOVE_TV_BOOKMARK";
export const ADD_MOVIE_BOOKMARK = "ADD_MOVIE_BOOKMARK";
export const REMOVE_MOVIE_BOOKMARK = "REMOVE_MOVIE_BOOKMARK";
export const SET_BOOKMARKS_FROM_STORAGE = "SET_BOOKMARKS_FROM_STORAGE";
